# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import fighters.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('opponent_last_5', models.CharField(blank=True, max_length=20)),
                ('opponent_record_before', models.CharField(blank=True, max_length=20)),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw'), ('NC', 'No contest')], max_length=2)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-details__date', '-ordinal'],
            },
        ),
        migrations.CreateModel(
            name='FightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('U', 'Upcoming'), ('P', 'Past')], max_length=1, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('A', 'Amateur'), ('E', 'Exhibition fight'), ('P', 'Professional')], max_length=1)),
                ('method', models.CharField(blank=True, max_length=128)),
                ('method_type', models.CharField(blank=True, choices=[('KO/TKO', 'KO/TKO'), ('SUBMISSION', 'SUBMISSION'), ('DECISION', 'DECISION'), ('OTHER', 'OTHER'), ('NC', 'NC'), ('DRAW', 'DRAW')], default=None, max_length=15, null=True)),
                ('round', models.CharField(blank=True, max_length=2)),
                ('time', models.CharField(blank=True, max_length=5)),
                ('referee', models.CharField(blank=True, max_length=255)),
                ('ordinal', models.IntegerField(blank=True, default=None, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='events.Event')),
            ],
            options={
                'verbose_name_plural': 'Fight details',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('birthplace', models.CharField(blank=True, max_length=50, verbose_name='Brith place')),
                ('country', django_countries.fields.CountryField(blank=True, db_index=True, default=None, max_length=2, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, verbose_name='Nationality')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('height', models.CharField(blank=True, max_length=6, verbose_name='Height')),
                ('height_imp', models.CharField(blank=True, max_length=6, verbose_name='Height imperial')),
                ('weight', models.CharField(blank=True, max_length=6, verbose_name='Weight')),
                ('weight_imp', models.CharField(blank=True, max_length=6, verbose_name='Weight imperial')),
                ('weight_class', models.CharField(blank=True, max_length=100, verbose_name='Weight class')),
                ('reach', models.CharField(blank=True, max_length=6, verbose_name='Reach')),
                ('team', models.CharField(blank=True, max_length=50, verbose_name='Team')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=fighters.models.fighter_images_directory_path)),
                ('ufc_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('in_ufc', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='FighterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=fighters.models.fighter_images_directory_path)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fighters.Fighter')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FighterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('last_5', models.CharField(blank=True, default='', max_length=20)),
                ('wins', models.IntegerField(blank=True, default=0, null=True)),
                ('losses', models.IntegerField(blank=True, default=0, null=True)),
                ('draws', models.IntegerField(blank=True, default=0, null=True)),
                ('nc', models.IntegerField(blank=True, default=0, null=True)),
                ('wins_ko_tko', models.IntegerField(blank=True, default=0, null=True)),
                ('wins_sub', models.IntegerField(blank=True, default=0, null=True)),
                ('wins_dec', models.IntegerField(blank=True, default=0, null=True)),
                ('wins_other', models.IntegerField(blank=True, default=0, null=True)),
                ('losses_ko_tko', models.IntegerField(blank=True, default=0, null=True)),
                ('losses_sub', models.IntegerField(blank=True, default=0, null=True)),
                ('losses_dec', models.IntegerField(blank=True, default=0, null=True)),
                ('losses_other', models.IntegerField(blank=True, default=0, null=True)),
                ('fighter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='fighters.Fighter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FighterUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ufc', models.URLField(blank=True, max_length=100, null=True, unique=True)),
                ('sherdog', models.URLField(blank=True, max_length=100, null=True, unique=True)),
                ('wiki', models.URLField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True, max_length=100)),
                ('instagram', models.URLField(blank=True, max_length=100)),
                ('youtube', models.URLField(blank=True, max_length=100)),
                ('twitter', models.URLField(blank=True, max_length=100)),
                ('fighter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='fighters.Fighter')),
            ],
            options={
                'verbose_name_plural': 'Fighter urls',
            },
        ),
        migrations.AddField(
            model_name='fight',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='fighters.FightDetails'),
        ),
        migrations.AddField(
            model_name='fight',
            name='fighter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='fighters.Fighter'),
        ),
        migrations.AddField(
            model_name='fight',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fighters.Fighter'),
        ),
        migrations.AlterUniqueTogether(
            name='fight',
            unique_together=set([('details', 'fighter', 'opponent')]),
        ),
    ]
