# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('promotion', models.CharField(blank=True, max_length=255)),
                ('sherdog_url', models.URLField(blank=True, max_length=255, null=True)),
                ('ufc_url', models.URLField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
